### ISSUE TITLE
It's difficult to get uniform results.

### ISSUE THREAD

**Issue by crocket** [webdriverio/webdrivercss#12]
1. I looked at webdriverjs, webdriverio, and webdriver JSON wire protocol, but I couldn't find a way to set the viewport size. Webdriver knows only of window size. Unless the viewport size is uniform, it's difficult to get uniform screenshots. How would you set the viewport size?
2. Also, I couldn't get full screenshots on many versions of chrome, firefox, and IE via protractor.
   So, I tried webdrivercss on chrome to see if it can take screenshots of CSS selectors.
   The result was that screenshots included scrollbar if CSS selector was wider than browser width.
   
   Below is an example screenshot that contains scrollbar.

![cloudlogin_divider current](https://cloud.githubusercontent.com/assets/748856/3696746/4f12806c-1395-11e4-85df-fa179701e446.png)

**Comment by iDVB** [comment]
"I am currently working on a new version of WebdriverCSS that takes uniform screenshots across different browser and selenium driver."

Have you gotten farther with this effort? We're desperately looking for this feature at the moment.

**Comment by christian-bromann** [comment]
Yes. I released v1 since then.

**Comment by iDVB** [comment]
Great! can you point me to how I can ensure Firefox and Chrome both take consistant screenshots of...
1) FIXED viewports at size 1024x768 
2) LONGSCROLL full body of site at 1024 width (and whatever height needed to capture full page)

?

**Comment by christian-bromann** [comment]
Sure, with WebdriverCSS you basically get two new screenshot commands:

```js
// init WebdriverIO
var client = require('webdriverio').remote({desiredCapabilities:{browserName: 'chrome'}})
// init WebdriverCSS
require('webdrivercss').init(client);

client
    .init()
    .url('http://example.com')
    .documentScreenshot('./fullScreenshot.png') // will be XXXXpx x XXXXpx depending on document size
    .setViewportSize({
        width: 1024,
        height: 768
    })
    .viewportScreenshot('./viewportScreenshot.png') // will be exactly 1024px x 768px
    .end();
```

**Comment by iDVB** [comment]
Is this a specific beta version?
When I run this code with webdrivercss 1.1.0, I get..
`TypeError: Object #<WebdriverIO> has no method 'documentScreenshot'`

**Comment by christian-bromann** [comment]
@iDVB oh sorry I was wrong with the command name. It is `saveViewportScreenshot` and `saveDocumentScreenshot`. I will update the example above.

**Comment by iDVB** [comment]
Thanks! Trying... Maybe add to readme as well? Did you also intend to `.init()` twice?

**Comment by iDVB** [comment]
nm... I see what you are doing...
I usually...
init the client before passing to webdrivercss
```
var client = webdriverio.remote({
        desiredCapabilities: {
            browserName: 'chrome',
            version: '41.0',
            platform: 'OS X 10.10',
            tags: ['examples'],
            name: 'OSX Chrome: Multi-Breakpoint'
        },
        host: 'ondemand.saucelabs.com',
        port: 80,
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        logLevel: 'silent'
    }).init();
 

// initialise WebdriverCSS for `client` instance
webdrivercss.init(client);

client
    .url('http://www.contrave.com/')
    .saveDocumentScreenshot('./ouput/chrome/fullScreenshot.png') // will be XXXXpx x XXXXpx depending on document size
    .setViewportSize({
        width: 1024,
        height: 768
    })
    .saveViewportScreenshot('./ouput/chrome/viewportScreenshot.png') // will be exactly 1024px x 768px
    .end();
```

You are doing it in the chain...
```
var client = webdriverio.remote({
        desiredCapabilities: {
            browserName: 'chrome',
            version: '41.0',
            platform: 'OS X 10.10',
            tags: ['examples'],
            name: 'OSX Chrome: Multi-Breakpoint'
        },
        host: 'ondemand.saucelabs.com',
        port: 80,
        user: process.env.SAUCE_USERNAME,
        key: process.env.SAUCE_ACCESS_KEY,
        logLevel: 'silent'
    });
 

// initialise WebdriverCSS for `client` instance
webdrivercss.init(client);

client
    .init()
    .url('http://www.cnn.com/')
    .saveDocumentScreenshot('./ouput/chrome/fullScreenshot.png') // will be XXXXpx x XXXXpx depending on document size
    .setViewportSize({
        width: 1024,
        height: 768
    })
    .saveViewportScreenshot('./ouput/chrome/viewportScreenshot.png') // will be exactly 1024px x 768px
    .end();
```

is there a difference?

**Comment by christian-bromann** [comment]
Nope there isn't. Just make sure you call `webdrivercss.init(client);` before using any of these two commands as they get added with the initialisation.

**Comment by iDVB** [comment]
any idea how these work on iPhone and iPad?

**Comment by christian-bromann** [comment]
It kinda should when running in hybrid but full mobile support is missing and something that is on the roadmap. We first need to improve the mobile skills for WebdriverIO though that will get tackled after `v3` release.

**Comment by iDVB** [comment]
Unfortunately, Not able to get this working...

```
RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Invalid method for resource: GET /wd/hub/session/172.20.47.85:4723:1002/window/current/size
Command duration or timeout: 205 milliseconds
Build info: version: '2.28.0', revision: '18364', time: '2013-01-10 00:47:46'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.6.8', java.version: '1.6.0_65'
Session ID: 172.20.47.85:4723:1002
Driver info: org.openqa.selenium.iphone.IPhoneDriver
Capabilities [{platform=MAC, databaseEnabled=true, javascriptEnabled=true, browserName=iPhone, webStorageEnabled=true, locationContextEnabled=true, takesScreenshot=true, version=5.0}]

     Callstack:
     -> windowHandleSize()
     -> setViewportSize({"width":1334,"height":750})

dvanbrunt-mbp-4:test dvanbrunt$
```

**Comment by iDVB** [comment]
I also tried this config....
```javascript
var webdriverio = require('webdriverio');
var webdrivercss = require('webdrivercss');

var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'iphone',
        platform: 'OS X 10.10',
        version: '8.2',
        deviceName: 'iPhone Simulator',
        deviceOrientation: 'portrait',
        name: 'Safari iOS: Remove ISI'
    },
    host: 'ondemand.saucelabs.com',
    port: 80,
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    logLevel: 'silent'
});
 
// initialise WebdriverCSS for `client` instance
webdrivercss.init(client);

client
    .init()
    .url('http://www.contrave.com/')
    .saveDocumentScreenshot('./output/iphone-fullScreenshot.png')
    .saveViewportScreenshot('./output/iphone-viewportScreenshot.png')
    .end();
```

... and got this as fixed viewport

![viewport](http://goo.gl/Jv0Gu9)

**Comment by christian-bromann** [comment]
@iDVB I would recommend to just use chrome for now and decrease the viewport to 400px width. I think there is no better solution for this at the moment unfortunately.

> it looks like SauceLabs does not have a way to set the iPhone model.... eg. iPhone 3, iPhone 5, iPhone 6, iPhone 6+ etc

You can't specify an iPhone model only the iOS version. Checkout the [platform-configurator](https://docs.saucelabs.com/reference/platforms-configurator) to get a better overview about capabilities.

**Comment by christian-bromann** [comment]
Using chrome you can play around with chrome flags to change the user agent and stuff like this.

**Comment by iDVB** [comment]
{Extreme sadness} Screenshoting chrome is what we do now manually. We made the move to Sauce both to solve this issue as well as to automate. 

Do you have any idea if the native selenium webdriver supports this? Maybe there is an in-term hack?

**Comment by iDVB** [comment]
btw... this kinda works.... and depending on how it works in landscape.... it may be the answer for us...
```
var webdriverio = require('webdriverio');
var webdrivercss = require('webdrivercss');

var client = webdriverio.remote({
    desiredCapabilities: {
        browserName: 'iphone',
        platform: 'OS X 10.10',
        version: '8.2',
        deviceName: 'iPhone Simulator',
        deviceOrientation: 'portrait',
        name: 'Safari iOS: Remove ISI'
    },
    host: 'ondemand.saucelabs.com',
    port: 80,
    user: process.env.SAUCE_USERNAME,
    key: process.env.SAUCE_ACCESS_KEY,
    logLevel: 'silent'
});
 

// initialise WebdriverCSS for `client` instance
webdrivercss.init(client);

client
    .init()
    .url('http://www.contrave.com/')
    .saveDocumentScreenshot('./output/iphone-fullScreenshot.png')
    .saveScreenshot('./output/iphone-viewportScreenshot.png')
    .end();
```

![iphone](http://goo.gl/DJe6iD)

**Comment by christian-bromann** [comment]
Yeah as I said it kinda works though you will run into issues regarding stitching screenshots together. Doing visual regression tests for native apps should work but there is a lot of stuff to take care of and a lot of work to get this out. WebdriverCSS will support native regression tests at one point though it will take a while without external help
