### ISSUE TITLE
Issue syncing down when repo is nested inside a directory

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdrivercss#124]
Where screenshotRoot is set to a repo inside one or more folders it fails to sync down when using the admin panel.

Set `screenshotRoot` equal to  `webdrivercss/webdrivercss-demo1`

Issue 1
Sync down returns a 404. 
The code is looking for `webdrivercss-demo1` in `repositories/webdrivercss` whereas the repo is in the root of `repositories`.

Issue 2
Sync, will download the repo to the root of the folder whereas I would expect it to be downloaded to `root/webdrivercss/`

examples of `screenshotRoot` paths which fail
`webdrivercss/webdrivercss-demo1`
`css/webdrivercss/webdrivercss-demo2`

**Comment by kevinmcdonnell** [comment]
@christian-bromann this is an issue preventing the use of the webdrivercss admin panel for nested image repositories. Not sure if other people have come across it..

Let me know what you think and I can fix up the coverage?

**Comment by christian-bromann** [comment]
Ok let's move convo to #125
