### ISSUE TITLE
Not saving screenshots

### ISSUE THREAD

**Issue by jenniferplusplus** [webdriverio/webdrivercss#13]
I am not able to get webdrivercss to save screenshots.  Below is the full script I am executing, slightly modified from the readme.

``` javascript
var client = require('webdriverjs').remote({desiredCapabilities:{browserName: 'firefox'}});
// init WebdriverCSS
require('webdrivercss').init(client);

client.init();
client.url('http://example.com');

client.saveScreenshot('example.png', null);
client.webdrivercss('example', null);
```

webdriverjs creates the expected screenshot 'example.png'.
webdrivercss creates the default screenshot directories (./webdrivercss/diff), but they contain no files.

Installed via npm with no errors reported.  Canvas also installed via npm with no errors.

Am I missing something?

Win7 x64
Node.js v0.10.30
JRE 1.8.0_11 64bit
selenium-server-standalone-2.42.4

**Comment by rishabhsrao** [comment]
I too was having the same issue of screenshot not getting created; the folders were getting created though. It turned out that I was using `webdriverio` v3.0. There's a note in the readme which says,

> Note: WebdriverCSS isn't yet compatible with WebdriverIO v3.0. We are currently working on it to make that happen soon. So stay tuned.

I switched to `webdriverio` v2.4.5 in my `package.json` and that resolved the issue.
