### ISSUE TITLE
Use webdrivercss without webdriverjs

### ISSUE THREAD

**Issue by richard-flosi** [webdriverio/webdrivercss#14]
Is it possible to use webdrivercss without webdriverjs?
Any hints on doing so?

**Comment by dandv** [comment]
@richard-flosi: I was intrigued by your comparison of Nightwatch with WebdriveIO and looked at the Nightwatch syntax on their home page:

```js
module.exports = {
  'Demo test Google' : function (client) {
    client
      .url('http://www.google.com')
      .waitForElementVisible('body', 1000)
      .assert.title('Google')
      .assert.visible('input[type=text]')
      .setValue('input[type=text]', 'rembrandt van rijn')
      .waitForElementVisible('button[name=btnG]', 1000)
      .click('button[name=btnG]')
      .pause(1000)
      .assert.containsText('ol#rso li:first-child',
        'Rembrandt - Wikipedia')
      .end();
  }
};
```

This is *very* verbose, compared to WebdriverIO. Have you seen the [comparison with selenium-webdriverjs and WD.js](https://github.com/webdriverio/webdriverio/issues/138#issuecomment-32051980)? Does Nightwatch have a comparably simple syntax?

**Comment by richard-flosi** [comment]
@dandv Nightwatch no longer requires the waitFor timeout param, you can set it globally. Can you provide a comparison example of what feels more verbose in Nightwatch compared to WebdriverIO? Their apis are both fluent and almost identical from what I remember.
