### ISSUE TITLE
Support for WebdriverIO v4.0 

### ISSUE THREAD

**Issue by YadrovSergey** [webdriverio/webdrivercss#150]
Is webdrivercss support WebdriverIO v4.0 ?

**Comment by christian-bromann** [comment]
Not yet but I will start working on this now.

**Comment by bennett000** [comment]
@christian-bromann have you had the time to make any progress on this?

**Comment by christian-bromann** [comment]
Yeah but it will take me a bit more time

**Comment by astoilkov** [comment]
Can we reopen this issue as I believe this is still not done and I want to track it so I can implement it the moment it gets done.
