### ISSUE TITLE
Screenshot on mobile devices

### ISSUE THREAD

**Issue by AxelHo** [webdriverio/webdrivercss#152]
If i test mobile devices  on saucelabs for example
desiredCapabilities: {
            platform: 'OS X 10.10',
            name: 'Applitools',
            version: '9.0',
            deviceName: "iPad Retina",
            deviceOrientation: "portrait"
        }

The stitching of the screenshot is not correct. The Browser Header and Footer is not removed.

![issue](https://cloud.githubusercontent.com/assets/3479780/15392929/7ec3ffb6-1dca-11e6-9445-1c9ac34c9e60.png)

**Comment by SamsonNelson** [comment]
I am having the same issue - I have attempted multiple options and couldn't get it. I ended up using the exclude as a work around. Not very pretty but its better than nothing I guess. If there is a known solution that would be amazing!

![tc_53682_buttons iphone6 gravy_component baseline](https://cloud.githubusercontent.com/assets/12635074/15582113/933f361a-232c-11e6-94a0-d352adbab7ff.png)

**Comment by AxelHo** [comment]
@SamsonNelson have a look at https://github.com/zinserjan/wdio-screenshot
It's still in development, but Jan promised to solve this problem

**Comment by AxelHo** [comment]
I jumped over to https://github.com/zinserjan/wdio-screenshot
