### ISSUE TITLE
How to keep the app open after launching it?

### ISSUE THREAD

**Issue by msneiQA** [webdriverio/webdrivercss#153]
Hello,
I am new to wdio and mobile automation.
I have created a simple project to launch the app. It is launching the app but it closes it immediately.
What should I do to keep it open till I give the client.end command in after function.
This is the test script : 
var webdriverio = require('webdriverio');

var client = webdriverio.remote();

describe('Simple cases', function () {
    this.timeout(300000);

    before(function () {
        return client.init();
    });

    describe("Test the App", function () {
        it("test-function", function () {
            //insert your test here
            console.log("inside 'test the app' test case ");
        });
    });

    after(function() {
        return client.end();
    });
    
});

**Comment by christian-bromann** [comment]
Just don't call end.

**Comment by msneiQA** [comment]
Yes, I tried hiding the code : return client.end();
still its closing the app.
Actually its minimizing it and appium inspector also doesn't load
