### ISSUE TITLE
4.0 support?

### ISSUE THREAD

**Issue by azaslavsky** [webdriverio/webdrivercss#156]
Hi,
  I noticed that there is a large disclaimer that 3.0 is not **yet** supported, but that the dependency in the package.json file is ^4.0.9?  Does this mean that 4.x+ is supported, but that this library is not yet backwards compatible with 3.x?  Or are neither 3.x nor 4.x supported?

**Comment by meleyal** [comment]
@azaslavsky I think 4.x support is happening in https://github.com/webdriverio/webdrivercss/tree/beta-rc1.

PR https://github.com/webdriverio/webdrivercss/pull/146 works with 4.x, but not sure how stable that is.

**Comment by meleyal** [comment]
Provisional Todo list:

- [ ] All commands have to be rewritten into async/await logic (see https://github.com/webdriverio/webdrivercss/commit/6036237d129de06f81161de934e2b4934ee29031, https://github.com/webdriverio/webdrivercss/pull/146)
- [ ] Update documentation
- [ ] Update [webdriverio examples](https://github.com/webdriverio/webdriverio/tree/master/examples)
- [ ] Update version/changelog (sync version with webdriverio?)
- [ ] Related issues?

@christian-bromann anything missing?

**Comment by azaslavsky** [comment]
Thanks for the response, @meleyal!

I ended up using [wdio-screenshot](https://github.com/zinserjan/wdio-screenshot) and [wdio-visual-regression-service](https://github.com/zinserjan/wdio-visual-regression-service) instead, which, as far as I have been able to tell, work great with 4.x.  The only downside is that their APIs are a little less robust than this one (no exclusions, for example), but I'm sure that will be fixed with time.

It's worth mentioning that they are both already written with async/await, so perhaps they could be used as dependencies for this library under the hood?

**Comment by meleyal** [comment]
@azaslavsky I also switched for now. There's an issue here about possibly merging the two projects: https://github.com/zinserjan/wdio-screenshot/issues/5

**Comment by mCzolko** [comment]
Hi,
what is the ETA on this?

**Comment by christian-bromann** [comment]
please see https://github.com/webdriverio/webdrivercss/issues/156#issuecomment-226279316
