### ISSUE TITLE
Badge for dependencies

### ISSUE THREAD

**Issue by paazmaya** [webdriverio/webdrivercss#158]
How about adding a badge that shows the status of their level of up to dateness?

Such as this https://david-dm.org/

For example installing the latest version reveals `npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the`

This might have been covered in case there would be a some kind of notification such as a badge, that dependencies are out of date.

**Comment by justinlevi** [comment]
@paazmaya is there a workaround for this error that you know of?

**Comment by paazmaya** [comment]
The PR #159 contains dependency updates that result in the following:

```
$ npm ls graceful-fs
webdrivercss@1.1.10
├─┬ babel-cli@6.10.1
│ └─┬ chokidar@1.5.2
│   └─┬ fsevents@1.0.12
│     └─┬ node-pre-gyp@0.6.25
│       └─┬ tar@2.2.1
│         └─┬ fstream@1.0.8
│           └── graceful-fs@4.1.3
└─┬ fs-extra@0.30.0
  └── graceful-fs@4.1.4
````

**Comment by paazmaya** [comment]
Goodbye
