### ISSUE TITLE
Is someone working on support for Webdriver.io 4?

### ISSUE THREAD

**Issue by presidenten** [webdriverio/webdrivercss#163]
Is this repo still maintained? And if so, is someone working on Webdriver.io 4 support?

**Comment by bennett000** [comment]
I did some digging on this issue a few months ago and found #150 and I was looking today and found #156 on the #156 thread there's mention of other similar, but less robust tools: https://github.com/webdriverio/webdrivercss/issues/156#issuecomment-226279316 

There are some active forks of the RC1 branch by the looks of it.

**Comment by christian-bromann** [comment]
This repository is not actively developed by me anymore. I don't have the time to do so and spend the small amount I have in improving the main webdriverio framework. However I haven't quit webdrivercss. I might update it eventually. Looking for someone who wants to actively work on it. We already have with `wdio-screenshot` a plugin that takes the screenshot so a whole bunch of code can be removed. What's left is the integration into applitools and other tools as well as providing multiple storage possibilities.
