### ISSUE TITLE
Compatible with selenium-webdriverjs?

### ISSUE THREAD

**Issue by lj9142** [webdriverio/webdrivercss#165]
This may be a silly question but is the webdrivercss tool compatible with selenium-webdriverjs? 

I am using webdriverio at the moment but am considering moving over to selenium webdriver and this tool is one of the most valuable for our regression testing.

Thanks!

**Comment by christian-bromann** [comment]
WebdriverCSS is not compatible with `selenium-webdriver`, you have to use WebdriverIO
