### ISSUE TITLE
Still maintained ?

### ISSUE THREAD

**Issue by jaydenlin** [webdriverio/webdrivercss#170]
Is this project still maintained ?

**Comment by JohnAlbin** [comment]
🤔 

![saychirpything](https://cloud.githubusercontent.com/assets/33429/23399976/47e32ed8-fddd-11e6-842d-d4a56a7ef154.gif)

**Comment by christian-bromann** [comment]
Please see https://www.npmjs.com/package/wdio-screenshot

**Comment by benzaita** [comment]
So that's a "no"? :-)
