### ISSUE TITLE
Can't build working package on linux

### ISSUE THREAD

**Issue by ipeshev** [webdriverio/webdrivercss#180]
grunt babel produces ./build folder, this folder is npm link-ed to another project after start it produces error 
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(fileName) {
                                             ^

ReferenceError: regeneratorRuntime is not defined
In general I'm triyng to get rid of webdriverio , your tool for taking snapshots and comparing them is awesome but webdriverio is a bit clumsy with browser interactions

**Comment by christian-bromann** [comment]
@ipeshev this project is deprecated and doesn't work with the latest webdriverio version anymore. Please use wdio-screenshot and the wdio-visual-regression-service. Thanks!
