### ISSUE TITLE
arguments to `webdrivercss` callback aren't documented

### ISSUE THREAD

**Issue by cvrebert** [webdriverio/webdrivercss#41]
https://github.com/webdriverio/webdrivercss#usage says you can pass in a `callback` argument, but doesn't state what arguments that callback will be invoked with.

The `res` argument appears to be an object mapping `name`s from the `webdrivercss` call to some array of objects of some type (which also isn't documented!) that has useful properties such as `isWithinMisMatchTolerance`.

**Comment by amitaibu** [comment]
I believe the arguments are ``err``, and ``res``. from the exmaple

```javascript
// ...
], function(err, res) {
        assert.ifError(err);
        assert.ok(res.header[0].isWithinMisMatchTolerance);
        assert.ok(res.hero[0].isWithinMisMatchTolerance);
    })
```

**Comment by christian-bromann** [comment]
@cvrebert is right. There is currently a lack of documentation here. Hope we can fix that soon. Looking for any kind of contribution.

**Comment by jamesdwilson** [comment]
+1
