### ISSUE TITLE
Generate Reports on Captured Images

### ISSUE THREAD

**Issue by TheSavior** [webdriverio/webdrivercss#58]
It would be nice to have a reporter that would output to a file, stats about the process.

For example:
1. the images that were taken
2. for each image, whether they are a baseline or diff
3. the images within or not within the tolerances

**Comment by christian-bromann** [comment]
@TheSavior these information are available if you pass a callback as last parameter and check the result. Since webdriverio/webdrivercss is test-framework-agnostic it is not applicable to implement sth like a reporter. I would recommend to console.log those information.
