### ISSUE TITLE
I got an error and I do not know how to do

### ISSUE THREAD

**Issue by Naixor** [webdriverio/webdrivercss#65]
```Java
spawn gm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
```

**Comment by TheSavior** [comment]
My guess is you don't have graphics magick installed. Have you followed the [install directions](https://github.com/webdriverio/webdrivercss#install)?

**Comment by Naixor** [comment]
i use `gm = require('gm').subClass({ imageMagick: true })` replaced `gm = require('gm')`, and it works well in mac

**Comment by TheSavior** [comment]
@Naixor, Interesting. I'm on Mac and don't have to do that.
