### ISSUE TITLE
Document `saveImages` option

### ISSUE THREAD

**Issue by anselmbradford** [webdriverio/webdrivercss#68]
https://github.com/webdriverio/webdrivercss/blob/master/lib/webdrivercss.js#L71 allows the passing in of a `saveImages` option, but this is undocumented in the readme.

**Comment by christian-bromann** [comment]
@anselmbradford `saveImages` is more an internal flag. It don't see why it should be useful to document it. If set to `true` it neither saves images on fs nor compares them. It saves computation if you are only interested in the byte stream of the screenshot. This is internally the case when the user uses Applitools.
