### ISSUE TITLE
Add "remove" command

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#69]
Currently there's `hide` but the element still takes it space. a `remove` could use `display: none`. My use case is for example hiding Disqus comments form a blog post page.

![shoov_gizra_com___screenshots_180](https://cloud.githubusercontent.com/assets/125707/7401632/665a1496-eece-11e4-82e3-cb98b82ec001.jpg)

**Comment by christian-bromann** [comment]
@amitaibu would choosing a more specific query solve that issue? I guess the disqus plugin isn't lying along the content above, right?

**Comment by amitaibu** [comment]
> would choosing a more specific query solve that issue?

No, I've tried it. 
If you check [this](http://www.gizra.com/content/cross-browser-visual-regression-with-shoov/) page (you might actually enjoy the post :wink:) ) you can see that if you select `#disqus_thread` and setting `visibility: hidden` there's still the gap, which might change as comments will be added. with `display: none` I'd be able to perform the regression testing as it will take no space.

**Comment by amitaibu** [comment]
btw, until we have a `remove` command, my work around is to use the `execute` command along with jQuery:

```js
  it('should show a blog post page',function(done) {
    client
      .url('http://www.gizra.com/content/cross-browser-visual-regression-with-shoov/')
      // Hide comments using jQuery.
      .execute("jQuery('#disqus_thread').hide();")
      .webdrivercss(testName, {
        name: 'blog-post-page'
      }, shoovWebdrivercss.processResults)
      .call(done);
  });
```

**Comment by christian-bromann** [comment]
@amitaibu took some time today to implement that. Will publish this + recent bugfixes today.

**Comment by amitaibu** [comment]
:+1:

**Comment by christian-bromann** [comment]
just published it `v1.1.0`

**Comment by amitaibu** [comment]
Wow, quickest feature request ever + the good surprise of removing cairo dependency. Thanks @christian-bromann !

**Comment by christian-bromann** [comment]
You know, if a feature definitely make sense we should not wait to get it out ;-) .. no but seriously I was a bit absence on this project and needed to get that dependency removal out
