### ISSUE TITLE
Cannot find module 'gm'

### ISSUE THREAD

**Issue by iDVB** [webdriverio/webdrivercss#70]
Looks like the 'gm' module has been added to the **devDependencies** when it should have been added to the **dependencies** as well or instead.

Now when trying to run a script with webdrivercss, it errors out with...
`Cannot find module 'gm'`
until I manually `npm install gm`

**Comment by psbanka** [comment]
Also encountering this issue.

**Comment by christian-bromann** [comment]
oh sorry my bad .. just published `v1.1.1` to fix that.
Thanks for letting me know @iDVB
