### ISSUE TITLE
saveDocumentScreenshot fails on parallel runs due to missing .tmp directory

### ISSUE THREAD

**Issue by pebbz** [webdriverio/webdrivercss#71]
Based on issue https://github.com/webdriverio/webdrivercss/issues/12

I'm trying to use saveDocumentScreenshot to take a full page screenshot consistently.  The function works perfectly on a single run.  

However, I want to be able to run my application in parallel processes and this is where it fails.  Seems the documentScreenshot.js file creates a .tmp directory, processes the image, and then immediately deletes the .tmp directory.  However, this causes a race condition when there is multiple processes and the first deletes the .tmp directory when the second one still needs it causing an error.

**Comment by christian-bromann** [comment]
@pebbz yes that won't work. I guess it shouldn't be difficult to assign a random tmp directory to that command.

**Comment by pebbz** [comment]
I was thinking the same thing.  I will attempt at a local change to simply add a random tmp directory under .tmp.  Would you be interested in a pull request?  Do you have any suggestions on creating the random directory name or would a node package like tmp be ok?

**Comment by christian-bromann** [comment]
If you could submit a PR that would be perfect. I would suggest to create a directory with a name like `.tmp-uuid` somewhere in the root project folder (`path.join(__dirname, '..', 'tmp-uuid')`). We already have a method for [creating an uuid](https://github.com/webdriverio/webdrivercss/blob/master/lib/webdrivercss.js#L25-L36) so just use that one and encapsulate it as a helper module.

I am currently busy working on `v3` of WebdriverIO so any help is highly appreciated ;-)

**Comment by christian-bromann** [comment]
@pebbz thanks again for your contribution!

**Comment by christian-bromann** [comment]
@pebbz publish to NPM (`v1.1.2`)

**Comment by pebbz** [comment]
Thanks for merging that in so quickly!
