### ISSUE TITLE
screenWidth results with wrong images

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#73]
`screenWidth` property on two different tests results with the all the files to have the images of the first test.

```js
describe('Search engine tests', function() {

  this.timeout(99999999);
  var client = {};

  before(function(done){
    client = shoovWebdrivercss.before(done, caps);
  });

  after(function(done) {
    shoovWebdrivercss.after(done);
  });

  it('should show the Google main search page',function(done) {
    client
      .url('https://www.google.com/?gfe_rd=cr&ei=ku8bVbG3K-SG8QeFmICQDg&gws_rd=cr&fg=1')
      .webdrivercss(testName, {
        name: 'google',
        screenWidth: [320,640,960]
      }, shoovWebdrivercss.processResults)
      .call(done);

  });

  it('should show the DuckDuckGo main search page',function(done) {
    client
      .url('https://duckduckgo.com/')
      .webdrivercss(testName, {
        name: 'duckduck',
        screenWidth: [320,640,960]
      }, shoovWebdrivercss.processResults)
      .call(done);

  });
});
```

So in the above example the `duckduck` images are actually showing the `google` images

**Comment by christian-bromann** [comment]
The problem here is that you are using the same `pageName`. If you execute the webdrivercss command with the same pageName, it remembers whether or not that page got captured with given screen size. If so it reuses that image.

**Comment by amitaibu** [comment]
The name is different (`google` and `duckduck`). If I remove the `screenWidth` then the results are as expected.

**Comment by christian-bromann** [comment]
oh sorry I was a bit unclear. You need to change `testName` in your duckduckgo test. As I said it doesn't take you screenshots because if you use the same page name it assumes that it already took a capture of that page.

**Comment by amitaibu** [comment]
But that seems to happen only with the `screenWidth`, as otherwise it will produce correct baseline names (assuming `testName == default`):

```
default.google.baseline.png
default.duckduckgo.baseline.png
```

**Comment by christian-bromann** [comment]
This is intentional since capturing multiple screen sizes can consume a lot of time.

**Comment by amitaibu** [comment]
Ok thanks - I'll add a comment to the README to clarify this.

**Comment by christian-bromann** [comment]
:+1:
