### ISSUE TITLE
baseline image is different from the "original" one

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#74]
Here's an example (taken from [this](https://github.com/amitaibu/ci-tests-twitter/blob/master/ui-tests/test/tests.js) example repo)

```js
it('should show a user page',function(done) {
  client
    .url('https://twitter.com/gizra_drupal')
    .webdrivercss('default', {
      name: 'user-page',
      remove: [
        // Remove the tweets as they change often.
        '.ProfileTweet',
        // Hide the signup modal in case it pops-up.
        '#signup-dialog',
        '.modal-enabled .modal-overlay'
      ],
      // Exclude (place a black rectangle).
      exclude: [
        '.ProfileNav-value',
        '.Trends',
        '.PhotoRail-headingText',
        '.PhotoRail-mediaBox .media-thumbnail'
      ]
    })
    .call(done);
});
```

after executing `mocha`, the results aren't as expected as the baseline image is cut in the middle (tested with phantomJs and browserStack on chrome). 

1)  `default.png`:

![default](https://cloud.githubusercontent.com/assets/125707/7481840/d3c89302-f37b-11e4-806f-bb27844dcbae.png)

2) `default.user-page.baseline.png`:

![default user-page baseline](https://cloud.githubusercontent.com/assets/125707/7481847/e26f3cee-f37b-11e4-9f08-68478723905a.png)

**Comment by christian-bromann** [comment]
I wasn't able reproduce this. I used your example script:

```js
var client = require('webdriverio').remote({
  desiredCapabilities: {
    browserName: 'chrome'
  }
});

require('./index.js').init(client);

client
  .init()
  .url('https://twitter.com/gizra_drupal')
  .pause(5000)
  .webdrivercss('default', {
    name: 'user-page',
    remove: [
      // Remove the tweets as they change often.
      '.ProfileTweet',
      // Hide the signup modal in case it pops-up.
      '#signup-dialog',
      '.modal-enabled .modal-overlay'
    ],
    // Exclude (place a black rectangle).
    exclude: [
      '.ProfileNav-value',
      '.Trends',
      '.PhotoRail-headingText',
      '.PhotoRail-mediaBox .media-thumbnail'
    ]
  }, function(err, res) {
    console.log(res['user-page']);
  })
  .end();
```

`default.user-page.baseline.png`:
![default user-page baseline](https://cloud.githubusercontent.com/assets/731337/7556817/172235a0-f781-11e4-8383-7e1f1c0dd4c1.png)

**Comment by amitaibu** [comment]
I've tried it on 2 macs - and got the trimmed version. I'll try it on another computer and report back :)

**Comment by christian-bromann** [comment]
I am using Mac too. Weird

**Comment by amitaibu** [comment]
I'll try to add the `5000 pause` I saw you've added.

**Comment by amitaibu** [comment]
@christian-bromann would it be ok to ask you to try to execute [this](https://github.com/amitaibu/ci-tests-twitter/blob/master/ui-tests/test/tests.js) test -- which is this exact same test integrated with shoov?

I keep getting the trimmed image, so I just want to confirm if it's a system issue, or a code one from my side.

**Comment by christian-bromann** [comment]
ahhh I spotted the problem: you've removed the signup dialog but it somehow still affected the page. I changed the test script like this:

```js
it('should show a user page',function(done) {
    client
      .url(url + '/gizra_drupal')
      .waitForVisible('#signup-dialog', 10000)
      .click('#signup-dialog button')
      .webdrivercss(testName, {
        name: 'user-page',
        remove: [
          // Remove the tweets as they change often.
          '.ProfileTweet',
          // Hide the signup modal in case it pops-up.
          '#signup-dialog',
          '.modal-enabled .modal-overlay',
          // Hide the spinner
          '.GridTimeline .has-more-items .spinner'
        ],
        // Exclude (place a black rectangle).
        exclude: [
          '.ProfileNav-value',
          '.Trends',
          '.PhotoRail-headingText',
          '.PhotoRail-mediaBox .media-thumbnail'
        ]
      }, console.log)
      .call(done);
  });
```

The result is what you actually was looking for:

![default](https://cloud.githubusercontent.com/assets/731337/7557143/7619a2f4-f78c-11e4-93cb-7b29f95e2dd3.png)

**Comment by amitaibu** [comment]
@christian-bromann nope I'm still getting it trimmed. I've tried it both on phantomsJS and BrowserStack with chrome.

I'll try tomorrow on another computer.

**Comment by amitaibu** [comment]
I've tried on two more computers, and the results are similar (on one computer one image was even trimmed more).

to reproduce:
Fork https://github.com/amitaibu/ci-tests-twitter and then:

```bash
phantomjs --webdriver=4444 &
cd ci-tests-twitter/ui-tests
npm i
mocha
```

**Comment by christian-bromann** [comment]
@amitaibu ok seems that I narrowed it down. WebdriverCSS cropped the shot according to the dimension of the `body` element (if no other element was defined). Since the left side of the Twitter page is a floating element it doesn't contribute to the body height. I fixed that and will publish the new version once I get a blue build.

**Comment by christian-bromann** [comment]
@amitaibu please try `v1.1.3` and let me know if it works

**Comment by amitaibu** [comment]
Indeed the 1.1.3 solves this issue (and it was good to know that we can actually use `elem` for such cases).

However I believe this introduced a nasty bug - when you don't specify an `elem` - the regression image replaces your baseline! 

(You can test with this example [repo](https://github.com/amitaibu/ci-tests-twitter/blob/master/ui-tests/test/tests.js))

**Comment by amitaibu** [comment]
@christian-bromann ^^

**Comment by christian-bromann** [comment]
@amitaibu I wasn't really able to reproduce this. Here is what I did:

- run [that](https://gist.github.com/christian-bromann/da7d02b1ebb7f187e8d8) script
- modified the baseline image
- rerun the test and got a regression image
- rerun again, no changes, nothing got overwritten

What am I doing wrong here?

I assume that the problem with the [repo](https://github.com/amitaibu/ci-tests-twitter/blob/master/ui-tests/test/tests.js) is that you are testing with multiple browser. Since the browserName isn't part of the image name the baseline image get's overwritten by the second browser. Does that make sense?

**Comment by amitaibu** [comment]
I'll check with your script. 

>  Since the browserName isn't part of the image name the baseline image get's overwritten by the second browser. 

I'll check that, but in my case the whole difference was the use of `elem` - when it was omitted I saw the bug.

**Comment by amitaibu** [comment]
@christian-bromann sorry, just something I'm not clear from your script:

```js
  var client = require('webdriverio').remote({
    desiredCapabilities: {
      browserName: 'chrome'
    }
  });
```

I guess it means it runs against a chrome webdriver - but not sure what are the steps needed for this to happen?

**Comment by amitaibu** [comment]
Just to answer my own question regarding using the chrome webdriver -- https://github.com/webdriverio/webdriverio/issues/113#issuecomment-29896726

@christian-bromann I've tested with your script an indeed it works fine. I'll keep this closed and if able to reproduce I'll open a new issue. Thanks again :)
