### ISSUE TITLE
client.webdrivercss does not capture screenshot with webdriverio v3.0.0

### ISSUE THREAD

**Issue by aahill50** [webdriverio/webdrivercss#83]
I'm in the process of updating my tests to use webdriverIO v3.0.0, but it seems that the webdrivercss command no longer works. It still manages to create the directory diff subdirectory, but it doesn't seem to be saving the actual screenshot. This is with the latest version of webdrivercss

**Comment by christian-bromann** [comment]
@aahill50 sorry for getting back to you so late. We are transitioning WebdriverCSS to use WebdriverIOv3. It takes a bit time as many parts are changing. I will let you know once we are done with that.

**Comment by kabirsikand** [comment]
What's the timeline on the WebdriverIOv3 support?
