### ISSUE TITLE
Pass the webdrivercss properties to the callback function

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#87]
In Shoov we'd like to allow users to tag different screenshots, for example:

```js
.webdrivercss(testName, {
  name: 'blog-post',
  tags: ['homepage', 'blog-post'] // <-- Arbitrary tags
```

For that the callback function of `webdrivercss` should get all the properties passed to the command.

**Comment by christian-bromann** [comment]
Let's continue this convo at #88
