### ISSUE TITLE
Wrong exclude rectangle on phantomjs/ explorer

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#93]
Running `mocha`on this [test](https://github.com/Gizra/drupal.org-shoov/blob/master/ui-tests/test/tests.js#L31) with phantomJS or with BroserStack on ie11 produces `excludes` that don't cover the entire element.

![default_homepage_homepage_baseline](https://cloud.githubusercontent.com/assets/125707/8773526/917c6f44-2edd-11e5-82e7-f5a19380625d.jpg)

**Comment by amitaibu** [comment]
@christian-bromann how about using CSS for the exclusion, instead of getting the absolute. We could set:

```css
color: transparent;
background: black;
```

**Comment by amitaibu** [comment]
(as `remove` for example is already "playing" with the dom)

**Comment by amitaibu** [comment]
I will try to mimic this behavior with the above example using `execute`, and lets see how it turns out...

**Comment by TheSavior** [comment]
You wouldn't be able to do polygonal exclude regions using CSS. But if IE isn't calculating the right size and offset of elements then that is going to be a larger problem than just for exclude regions and should definitely be fixed.

**Comment by amitaibu** [comment]
@TheSavior

Sorry, indeed I forgot to mention it will not work for polygonal. 

> But if IE isn't calculating the right size and offset of elements then that is going to be a larger problem

It seems we are using `getBoundingClientRect` to get the values - which _seems_ to be the right way, although in the end result many times I see IE not excluding properly.

**Comment by amitaibu** [comment]
On the other hand, if there's a way to "fix" `getBoundingClientRect`, I'd be happy to continue with the good old `shot.drawRectangle()` way ;)

**Comment by christian-bromann** [comment]
Interesting for sure that all exclude rectangles have the same padding to the desired position. I bet there is some document margin not included in that `getBoundingClientRect` function.

@amitaibu how about doing both? Using CSS to make background black (would not work for certain elements though) + using `drawRectangle`

**Comment by amitaibu** [comment]
> I bet there is some document margin not included in that getBoundingClientRect function.

You mean some CSS element that messes with it? Not sure how to find it - can you [spot](https://www.drupal.org/) it?

> how about doing both?

Well, I'd argue that having one system that simply works should be fine ;)

I think we should try to find the cause - maybe it's something we can over come without removing `shot.drawRectangle()` as indeed now that you mention it, with CSS it might be tricky to do on some elements flash, svg, etc' :/

**Comment by amitaibu** [comment]
+ thank you guys for the quick replys ;)

**Comment by amitaibu** [comment]
With the risk of saying something stupid (won't be a first time :wink: ) - If I understand correctly [getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) is relative to the current view port not the absolute value.Looking at [this](https://github.com/webdriverio/webdrivercss/blob/77dd5002f445ac12c116fcfbfe33f793d73aaca0/lib/getPageInfo.js#L159-L165) part, could we be missing the scroll value?

**Comment by amitaibu** [comment]
So... I think I found the problem - the gap we are seeing is the scrollbar.

![dashboard](https://cloud.githubusercontent.com/assets/125707/8812435/ba82ee18-3004-11e5-97de-bc8e1eb35c5c.jpg)

The webdriverCSS image doesn't include the scrollbar, thus we can see a bigger padding on the document.

I've done some careful testing to confirm this Browsing the site directly via ie11 (using browserStack):

![dashboard](https://cloud.githubusercontent.com/assets/125707/8811938/f94e39d4-3001-11e5-98f8-7645a34a5db9.jpg)

Printing the values of `excludeRect` we see we got the right values:
```javascript
{ x0: 139.6600036621094,
    y1: 891.969970703125,
    x1: 287.2799987792969,
    y0: 862.6099853515625 }
```

Using CSS to place an element using `absolute` to position a rectangle on those same coords:

![dashboard](https://cloud.githubusercontent.com/assets/125707/8812236/94774a4e-3003-11e5-8bbc-e12ae370b9fe.jpg)

**Comment by amitaibu** [comment]
Ouch, I've added `document.body.style.overflow = 'hidden';` to hide the scrollbar, but the exclude is still placed wrong :/

**Comment by TheSavior** [comment]
Try `-ms-overflow-style: none`, that will hide the scrollbar in IE.

**Comment by christian-bromann** [comment]
maybe [getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) gets calculated on render time. :+1: for the finding @amitaibu

**Comment by amitaibu** [comment]
Ok, last info before letting this go for tonight...

On BrowserStack the resolution is set to 1024x768. However, when checking the max width we see it's 1007px with the scrollbar, and upon `document.body.style.overflow = 'hidden';` it is set to 1024px. So even though it's not working, I still think it's the scrollbar ;)

![dashboard](https://cloud.githubusercontent.com/assets/125707/8812800/f0e1c9d2-3006-11e5-9ead-9adb76fb6502.jpg)

**Comment by christian-bromann** [comment]
yeah seems like it. Actually it would be no problem to remove the scrollbar because we scroll using css as well

**Comment by amitaibu** [comment]
So I'm able to remove the scrollbar, but the values from `getBoundingClientRect()` are indeed the same. 

```javascript
    client
      .url(baseUrl)
      .execute(function() {
        document.body.style.overflow = 'hidden';
      })
      .webdrivercss(testName, {
        name: 'homepage',
        exclude:['#community-stats .users .highlight'],
  // ...
```

**Comment by christian-bromann** [comment]
Could you try `-ms-overflow-style: none` too?

**Comment by TheSavior** [comment]
I would not recommend setting overflow on the body to hidden. My guess is that if there are any scrolling elements this will be a problem so applying this to body isn't right. I'd really recommend trying

```
* {
  -ms-overflow-style: none;
}
```

**Comment by amitaibu** [comment]
@christian-bromann do you mean something like `document.body.style.-ms-overflow-style='none';`?

**Comment by amitaibu** [comment]
meh, too late, not thinking right ^^ ;)

`jQuery('body').css('-ms-overflow-style', 'none');` didn't have an effect. But do you think there's a difference from doing `document.body.style.overflow = 'hidden';` which is working fine?

**Comment by amitaibu** [comment]
Doing manually getBoundingClientRect() after hiding the scrollbar seems to return new values. 

![dashboard](https://cloud.githubusercontent.com/assets/125707/8813069/1b037dee-3009-11e5-96e4-70ab4cabc319.jpg)

So if I'm indeed right about this, then the next thing is to figure out why getBoundingClientRect() doesn't return the updated one when running via webdriverCSS

**Comment by christian-bromann** [comment]
there are the 9px :wink:

**Comment by amitaibu** [comment]
yeah, one pixel for each hour I lost on finding it :wink:

**Comment by christian-bromann** [comment]
haha, so but this is not working using the `execute` command?

**Comment by christian-bromann** [comment]
btw: thanks for figuring that out :+1:

**Comment by amitaibu** [comment]
Sure :)

>  so but this is not working using the execute command?

Unfortunately no. The weird thing is that the image we get from webdriverCSS doesn't have the vetical scrollbar even without the `execute` I've added.

**Comment by amitaibu** [comment]
@christian-bromann if you'd like I can add you to my BrowserStack account if you want to experiment.

(It's getting late, and I actually attend a conf about Shoov tomorrow :smile: )

**Comment by christian-bromann** [comment]
wait I got it

**Comment by amitaibu** [comment]
waiting... :)

**Comment by christian-bromann** [comment]
So here is the problem: https://github.com/webdriverio/webdrivercss/blob/master/lib/documentScreenshot.js#L101-L119

before I take the screenshot I do that overflow hidden thing already but remove it after taking the screenshot and before executing getBoundingClientRect().

**Comment by christian-bromann** [comment]
I guess we need to capture these information while being in that capturing state. Doesn't look like an easy refactor though :-/

**Comment by amitaibu** [comment]
what do you mean by 

> but remove it after taking the screenshot and before executing getBoundingClientRect()

Remove what?

**Comment by christian-bromann** [comment]
when I take the screenshot I remove the scrollbars and enable them after taking the screenshot. Then the next step ist to capture the position information (with scrollbars enabled instead of disabled)

**Comment by amitaibu** [comment]
why do you need to re-enable them?

**Comment by christian-bromann** [comment]
good question..I think it might be better to leave the page as it is as much as possible. Not sure if this is necessary though

**Comment by christian-bromann** [comment]
page might behave differently with scrollbars disabled. This could affect the next capturing process/screenshot.

**Comment by amitaibu** [comment]
meh, your messing with the dom anyway with `remove`, and possible with `execute`.

In fact, removing `document.body.style.overflow = 'visible';` has fixed the problem!

**Comment by christian-bromann** [comment]
> you'r messing with the dom anyway with remove

not quite, I just set `display: none` and enable it after the capturing process. But yeah I guess this solves definitely some displacement issues \o/ .. glad it works now.

**Comment by amitaibu** [comment]
But you'll accept a PR to remove the re-enabling, right? :)

**Comment by amitaibu** [comment]
well, I'm out for today..

**Comment by christian-bromann** [comment]
We should think of a better strategy for the capturing process instead of just removing a line of code.

**Comment by christian-bromann** [comment]
ok, good night and thanks again!

**Comment by amitaibu** [comment]
:+1:

**Comment by amitaibu** [comment]
> We should think of a better strategy for the capturing process instead of just removing a line of code.

What would be the implication of that removal? As far as I can see, even as a short term solution it would be preferable than having that offset almost constantly on IE.
