### ISSUE TITLE
Can we use Chrome's device emulation capabilities

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#95]
![new_issue_and_gizra_modli-shoov](https://cloud.githubusercontent.com/assets/125707/8871150/e66276ea-31fb-11e5-91f4-3f8419ad49a7.jpg)

I couldn't find much info about it.

**Comment by christian-bromann** [comment]
I sure it is possible with the right chrome options. I haven't checked that out yet.

**Comment by amitaibu** [comment]
Ok,I'll check. Would be super useful!

**Comment by amitaibu** [comment]
Well, seems that SauceLabs and BrowserStack give these options already, so closing issue

![run_node_js_selenium_tests_in_the_cloud__700__desktop_and_mobile_browsers_](https://cloud.githubusercontent.com/assets/125707/8882284/753ae3be-324e-11e5-92d8-d96b852bf5b9.jpg)

**Comment by amitaibu** [comment]
Here's a better link - http://stackoverflow.com/a/26295660/750039
