### ISSUE TITLE
Many failueres due to setViewportSize

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#98]
The following error keeps happening in BrowserStack. For example:

```
Uncaught RuntimeError
(UnknownError:13) An unknown server-side error occurred while processing the command.
Problem: unknown error: result was not received in 10 seconds

Callstack:
-> windowHandleSize({"width":-896,"height":769})
-> setViewportSize({"width":640,"height":697})
```

@christian-bromann I'm looking to extend the 10 sec wait, but I'm not clear where I can define it - are you familiar with this?

**Comment by amitaibu** [comment]
I believe it's coming from the chromedriver, but still haven't figured out how to change it - or more importantly -- why it's taking over 10 sec ;)

**Comment by amitaibu** [comment]
Does it even make sense to see a negative value here? `-> windowHandleSize({"width":-896,"height":769})`

Could it be the cause for the hang?

**Comment by amitaibu** [comment]
I was able to reproduce locally, and see that indeed a negative width value results with the error.

**Comment by amitaibu** [comment]
Update: It's probably related to webdriverio not css, as it's related to [setViewportSize](https://github.com/webdriverio/webdriverio/blob/1ecdf18ea774d4003391b3fc2c14733fb4ea72e7/lib/commands/setViewportSize.js#L83).

And I was able to reproduce the error from time to time and see for example this sequence:

```
{ width: 1024, height: 840 }
{ width: 320, height: 769 }
{ width: 1648, height: 840 }
{ width: -928, height: 769 }
```

So the 5th iteration never happend.

**Comment by christian-bromann** [comment]
webdrivercss still runs on `2.4.5` so that change shouldn't be the root cause of the problem

**Comment by amitaibu** [comment]
The solution I've found (without digging into why we got the negative value was to change this line):

`width: Math.abs(windowHandle.width),` - and the test was able to continue. If it seems right to you I can write a proper PR (against the correct version of course).

**Comment by amitaibu** [comment]
+ Damn, it's good to finally tackle all those annoying issues. I'm really looking forward to having webdriverCSS leverage v3 - promises are so much readable than those crazy callbacks ;)

**Comment by christian-bromann** [comment]
> I'm really looking forward to having webdriverCSS leverage v3

totally agree. Had not much time for open source work recently but this will change in two weeks \o/

**Comment by amitaibu** [comment]
[Here's](https://github.com/webdriverio/webdriverio/blob/v2.4.5/lib/protocol/windowHandleSize.js#L64) the line I've changed.

If I create PR against which branch. Seems master is v3, but no v2 branch.

Anyway, I'm out for tonight :)

**Comment by amitaibu** [comment]
:+1:

**Comment by christian-bromann** [comment]
Feel free to open a PR based on the current master. Thanks!
