### ISSUE TITLE
webdrivercss doesn't save screenshots

### ISSUE THREAD

**Issue by bmxpala** [webdriverio/webdrivercss#99]
I am new to webdriverio and webdrivercss.. I need to make a screenshot of the some DOM element. So, I installed 'webdriverio', 'webdrivercss', 'graphicsmagick' by 'homebrew'  and wrote following test:

    // init WebdriverIO
    var client = require('webdriverio').remote({desiredCapabilities:{browserName: 'firefox'}});
    // init WebdriverCSS
    require('webdrivercss').init(client);
    client
       .init()
       .url('http://webdriver.io/')
       .webdrivercss('startpage',[
         {
             name: 'header',
             elem: '.mainnav'
         }
         ], function(err, res) {
              console.log(err, res);
         })
        .end();

As a result I got just empty ./webdrivercss directory and 'err', 'res' callback params as 'undefined' values. Do I do sth wrong?

MacOSX Yosemite, Node 'v0.12.7'.

**Comment by bmxpala** [comment]
Sorry, I didn't see that you don't support webdriverio v3.0.0 and higher. 
All works.

**Comment by christian-bromann** [comment]
> don't support webdriverio v3.0.0

yup, we are working on it to get this ported
